ProjetoIFSP/ProjetoIFSP/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoIFSP.Models;
using ProjetoIFSP.Repositorio;
using System.Diagnostics.Contracts;

namespace ProjetoIFSP.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepositorio _clienteRepositorio;
        public ClienteController(IClienteRepositorio clienteRepositorio)
        {
            _clienteRepositorio = clienteRepositorio;
        }
        public IActionResult Index()
        {
            List<ClienteModel> clientes = _clienteRepositorio.GetAll();
            return View(clientes);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            ClienteModel cliente = _clienteRepositorio.ListarPorId(id);
            return View(cliente);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            ClienteModel cliente = _clienteRepositorio.ListarPorId(id);
            return View(cliente);
        }

        public IActionResult Apagar(int id)
        {
            _clienteRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(ClienteModel cliente)
        {
            _clienteRepositorio.Adicionar(cliente);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(ClienteModel cliente)
        {
            _clienteRepositorio.Atualizar(cliente);
            return RedirectToAction("Index");
        }
    }
}

ProjetoIFSP/ProjetoIFSP/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoIFSP.Models;
using ProjetoIFSP.Repositorio;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoIFSP.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }
        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuarioRepositorio.GetAll();
            return View(usuarios);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.ListarPorId(id); 
            return View(usuario);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.ListarPorId(id);
            return View(usuario);
        }
        public IActionResult Apagar(int id)
        {
            _usuarioRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            _usuarioRepositorio.Adicionar(usuario);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Alterar(UsuarioModel usuario)
        {
            _usuarioRepositorio.Atualizar(usuario);
            return RedirectToAction("Index");
        }
    }
}

ProjetoIFSP/ProjetoIFSP/Views/Shared/Componentes/Menu/Default.cshtml
@model UsuarioModel

<a action="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Logado: @Model.Nome</a>
<ul class="navbar-nav flex-grow-1">
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre</a></li>
            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contato</a></li>
            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuários</a></li>
            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a></li>
            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a></li>
        </ul>
    </div>
</ul>